// WEEK 9 / 15.03 
const currentList = ["!Fo!Wphvf!!!Epo(u!Mfu!Hp!)Mpwf*!", "!V3!!!Ejtdpuifrvf!", "!Nbepoob!!!Epo(u!Dsz!Gps!Nf!Bshfoujob!", "!Op!Epvcu!!!Epo(u!Tqfbl!", "!Efqfdif!Npef!!!Cbssfm!Pg!B!Hvo!", "!Hjovxjof!!!Qpoz!", "!Xijuofz!Ipvtupo!!!Tufq!Cz!Tufq!", "!Npotubst!)C!Sfbm-!Cvtub!Siznft-!Dppmjp-!MM!Dppm!K…Nfuipe!Nbo*!!!Iju!(Fn!Ijhi!)Uif!Npotubst!Bouifn*!", "!ND!Mzuf!!!Dpme!Spdl!B!Qbsuz!", "!Bqpmmp!Gpvs!Gpsuz!!!Bjo(u!Ubmljo(!(Cpvu!Evc!", "!Tbti\"!!!Fodpsf!vof!gpjt!", "!Xbssfo!H/!!!J!Tipu!Uif!Tifsjgg!", "!CCF!!!Gmbti!", "!Tqjdf!Hjsmt!!!3!Cfdpnf!2!", "!Upoj!Csbyupo!!!Vo.Csfbl!Nz!Ifbsu!", "!Cbdltusffu!Cpzt!!!Bozxifsf!Gps!Zpv!", "!Kbnjsprvbj!!!Dptnjd!Hjsm!", "!S/!Lfmmz!!!J!Cfmjfwf!J!Dbo!Gmz!", "!Bfsptnjui!!!Gbmmjoh!Jo!Mpwf!)Jt!Ibse!Po!Uif!Lofft*!", "!Xijuf!Upxo!!!Bcpsu-!Sfusz-!Gbjm@!Zpvs!Xpnbo!"];
const nextList = ["!Fo!Wphvf!!!Epo(u!Mfu!Hp!)Mpwf*!", "!V3!!!Ejtdpuifrvf!", "!Nbepoob!!!Epo(u!Dsz!Gps!Nf!Bshfoujob!", "!Npotubst!)C!Sfbm-!Cvtub!Siznft-!Dppmjp-!MM!Dppm!K…Nfuipe!Nbo*!!!Iju!(Fn!Ijhi!)Uif!Npotubst!Bouifn*!", "!Efqfdif!Npef!!!Cbssfm!Pg!B!Hvo!", "!Op!Epvcu!!!Epo(u!Tqfbl!", "!Bqpmmp!Gpvs!Gpsuz!!!Bjo(u!Ubmljo(!(Cpvu!Evc!", "!Tbti\"!!!Fodpsf!vof!gpjt!", "!Hjovxjof!!!Qpoz!", "!Xijuofz!Ipvtupo!!!Tufq!Cz!Tufq!", "!Cbdltusffu!Cpzt!!!Bozxifsf!Gps!Zpv!", "!Xbssfo!H/!!!J!Tipu!Uif!Tifsjgg!", "!CCF!!!Gmbti!", "!ND!Mzuf!!!Dpme!Spdl!B!Qbsuz!", "!S/!Lfmmz!!!J!Cfmjfwf!J!Dbo!Gmz!", "!Sfqvcmjdb!!!Sfbez!Up!Hp!", "!Xijuf!Upxo!!!Bcpsu-!Sfusz-!Gbjm@!Zpvs!Xpnbo!", "!Bfsptnjui!!!Gbmmjoh!Jo!Mpwf!)Jt!Ibse!Po!Uif!Lofft*!", "!Ufybt!!!Tbz!Xibu!Zpv!Xbou!", "!Cmvs!!!Cffumfcvn!"]; 

const advertisement = {
  endSeconds: 91,
  name: "ADVERTISEMENT",
  startSeconds: 77,
  style: {width: "83vw"},
  videoId: 'caaddLZhLoY',
  volume: 50,
};

const intro = {
  name: "INTRO",
  style: {width: "83vw"},
  videoId: 'YoqgOOQwEqI',
  volume: 50,
};

const newVideo = {
  endSeconds: 20,
  name: "STING NEW VIDEO",
  startSeconds: 11,
  style: {width: "83vw"},
  videoId: 'caaddLZhLoY',
  volume: 50,
};

const sting = {
  name: "STING",
  startSeconds: 16,
  style: {width: "83vw"},
  videoId: 'YoqgOOQwEqI',
  volume: 50,
};

const charted = [
  {
    title: "All I Have To Give",
    artist: "Backstreet Boys",
    history: [3, 4, 5, 7, 10, 14],
    match: "!Uif!Qspejhz!!!Csfbuif!",
    startSeconds: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "pj6FCKm8dhM",
    volume: 100,
  },
  {
    title: "All Or Nothing",
    artist: "Cher",
    endSeconds: 242,
    history: [16, 14, 10, 8],
    match: "!Npotubst!)C!Sfbm-!Cvtub!Siznft-!Dppmjp-!MM!Dppm!K…Nfuipe!Nbo*!!!Iju!(Fn!Ijhi!)Uif!Npotubst!Bouifn*!",
    startSeconds: 6,
    style: {left: "-5vw", position: "relative", width: "110vw"},
    type: 0,
    videoId: "BW4LUe2e5oU",
    volume: 100,
  },
  {
    title: "All Star",
    artist: "Smash Mouth",
    history: [14, 9, 4, 1, 1, 1, 1, 1, 3],
    match: "!Nbepoob!!!Epo(u!Dsz!Gps!Nf!Bshfoujob!",
    style: {width: "100vw"},
    type: 0,
    videoId: "L_jWHffIx5E",
    volume: 100,
  },
  {
    title: "Angels",
    artist: "Robbie Williams",
    endSeconds: 235,
    history: [20, 11, 8, 5, 3, 2, 2, 3, 7],
    match: "!Xijuofz!Ipvtupo!!!Tufq!Cz!Tufq!",
    startSeconds: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "luwAMFcc2f8",
    volume: 100,
  },
  {
    title: "Atrapados En La Red",
    artist: "Tam Tam Go!",
    history: [15],
    match: "!Epoob!Mfxjt!!!J!Mpwf!Zpv!Bmxbzt!Gpsfwfs!",
    style: {width: "83vw"},
    type: 0,
    videoId: "u8uup17RrUU",
    volume: 100,
  },
  {
    title: "Baby One More Time",
    artist: "Britney Spears",
    history: [19, 20],
    match: "!Qfufs!Boesf!!!J!Gffm!Zpv!",
    style: {width: "83vw"},
    type: 0,
    videoId: "fHPnGqXXUmI",
    volume: 100,
  },
  {
    title: "Blue Monday",
    artist: "Orgy",
    history: [17, 15, 20, 20],
    match: "!Upsj!Bnpt!!!Qspgfttjpobm!Xjepx!",
    startSeconds: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "aJZTfl3DmCU",
    volume: 100,
  },
  {
    title: "Coffee And TV",
    artist: "Blur",
    endSeconds: 368,
    history: [15, 11],
    match: "!Tbti\"!!!Fodpsf!vof!gpjt!",
    startSeconds: 7,
    style: {width: "100vw"},
    type: 0,
    videoId: "GXRVX1AKAew",
    volume: 100,
  },
  {
    title: "Crazy",
    artist: "Britney Spears",
    endSeconds: 197,
    history: [16],
    match: "!Cbdltusffu!Cpzt!!!Bozxifsf!Gps!Zpv!",
    style: {width: "83vw"},
    type: 0,
    videoId: "IPL_4ICbrfw",
    volume: 100,
  },
  {
    title: "Diselo Con Flores",
    artist: "Fey",
    history: [19, 18],
    match: "!S/!Lfmmz!!!J!Cfmjfwf!J!Dbo!Gmz!",
    style: {width: "83vw"},
    type: 0,
    videoId: "r-b495ayDF4",
    volume: 100,
  },
  {
    title: "Don't Say You Love Me",
    artist: "M2M",
    history: [19, 16, 13, 19],
    match: "!Fbtu!28!!!Ifz!Dijme!!",
    style: {width: "83vw"},
    type: 0,
    videoId: "ZCFlT_FYnEE",
    volume: 100,
  },
  {
    title: "Fast As You Can",
    artist: "Fiona Apple",
    history: [20, 20, 18, 17, 17],
    match: "!MM!Dppm!K!!!Bjo(u!Opcpez!",
    style: {width: "83vw"},
    type: 0,
    videoId: "NbxqtbqyoRk",
    volume: 100,
  },
  {
    title: "Fly Away",
    artist: "Lenny Kravitz",
    history: [20, 11, 7, 2],
    left: "-5vw",
    match: "!V3!!!Ejtdpuifrvf!",
    style: {left: "-5vw", position: "relative", width: "110vw"},
    type: 0,
    videoId: "EvuL5jyCHOw",
    volume: 100,
  },
  {
    title: "Heartbreaker",
    artist: "Mariah Carey",
    history: [9, 12, 16],
    match: "!Uif!Csbjet!!!Cpifnjbo!Sibqtpez!!",
    style: {width: "83vw"},
    type: 0,
    videoId: "FUzcLVyFLNo",
    volume: 100,
  },
  {
    title: "Higher",
    artist: "Creed",
    history: [6, 5, 7, 8, 12, 17],
    match: "!Gvhfft!!!Op!Xpnbo!Op!Dsz!",
    style: {width: "83vw"},
    type: 0,
    videoId: "J16lInLZRms",
    volume: 100,
  },
  {
    title: "I Don't Want To Miss A Thing",
    artist: "Aerosmith",
    history: [13],
    match: "!CCF!!!Gmbti!",
    style: {width: "83vw"},
    type: 0,
    videoId: "JkK8g6FMEXE",
    volume: 100,
  },
  {
    title: "I Need To Know",
    artist: "Marc Anthony",
    history: [18, 10, 6, 2, 2, 3, 4, 4, 5],
    match: "!Op!Epvcu!!!Epo(u!Tqfbl!",
    style: {width: "83vw"},
    type: 0,
    videoId: "fLVzw9wVd9o",
    volume: 100,
  },
  {
    title: "If Ya Gettin' Down",
    artist: "Five",
    history: [7, 7, 9, 11, 15],
    match: "!Cbdltusffu!Cpzt!!!Rvju!Qmbzjoh!Hbnft!)Xjui!Nz!Ifbsu*!",
    style: {width: "83vw"},
    type: 0,
    videoId: "TU-5FmsXOOA",
    volume: 100,
  },
  {
    title: "Jennifer Del Estero",
    artist: "Illya Kuryaki",
    history: [12, 14, 18],
    match: "!Uif!Bsujtu!Gpsnfsmz!Lopxo!Bt!Qsjodf!!!Cfudib!Cz!Hpmmz!Xpx\"!",
    style: {width: "83vw"},
    type: 0,
    videoId: "KLRlJ0uJ-yI",
    volume: 100,
  },
  {
    title: "Keep On Movin'",
    artist: "Five",
    history: [19],
    match: "!Bfsptnjui!!!Gbmmjoh!Jo!Mpwf!)Jt!Ibse!Po!Uif!Lofft*!",
    style: {width: "83vw"},
    type: 0,
    videoId: "3OJMjlzVLZE",
    volume: 100,
  },
  {
    title: "La Lola",
    artist: "Cafe Quijano",
    history: [4, 6, 10, 16],
    match: "!Nbsl!Pxfo!!!Dijme!",
    style: {width: "83vw"},
    type: 0,
    videoId: "ccsUjRhpo_U",
    volume: 100,
  },
  {
    title: "Look At Me",
    artist: "Geri Halliwell",
    history: [16],
    match: "!Tqjdf!Hjsmt!!!Tbz!Zpv(mm!Cf!Uifsf!",
    style: {width: "83vw"},
    type: 0,
    videoId: "31mlEEs9_Vk",
    volume: 100,
  },
  {
    title: "Man! I Feel Like A Woman",
    artist: "Shania Twain",
    history: [20, 18, 14, 12, 12, 18],
    match: "!Cpz{pof!!!B!Ejggfsfou!Cfbu!",
    style: {width: "83vw"},
    type: 0,
    videoId: "ZJL4UGSbeFg",
    volume: 100,
  },
  {
    title: "Maria Maria",
    artist: "Santana",
    history: [19, 8, 8, 4],
    match: "!Efqfdif!Npef!!!Cbssfm!Pg!B!Hvo!",
    style: {width: "83vw"},
    type: 0,
    videoId: "nPLV7lGbmT4",
    volume: 100,
  },
  {
    title: "Mi Chico Latino",
    artist: "Geri Halliwell",
    left: "-5vw",
    history: [15, 12, 8, 4, 3, 2, 1],
    match: "!Fo!Wphvf!!!Epo(u!Mfu!Hp!)Mpwf*!",
    startSeconds: 1,
    style: {left: "-5vw", position: "relative", width: "110vw"},
    type: 0,
    videoId: "4KGTR0NPNF0",
    volume: 100,
  },
  {
    title: "New",
    artist: "No Doubt",
    history: [18, 12, 9, 7, 6, 6, 6, 9],
    match: "!ND!Mzuf!!!Dpme!Spdl!B!Qbsuz!",
    startSeconds: 2,
    style: {width: "83vw"},
    type: 0,
    videoId: "LTfD2E0hf4k",
    volume: 100,
  },
  {
    title: "No Quiero Verte",
    artist: "Lynda",
    history: [19, 17, 13, 11, 11, 15],
    left: "-5vw",
    match: "!Toppq!Ephhz!Ephh!gfbu/!Dibsmjf!Xjmtpo!!!Toppq(t!Vqtjef!Zb!Ifbe!",
    startSeconds: 1,
    style: {left: "-5vw", position: "relative", width: "110vw"},
    type: 0,
    videoId: "_o0vOmL-PYY",
    volume: 100,
  },
  {
    title: "Puente",
    artist: "Gustavo Cerati",
    history: [1, 1, 1, 4, 5, 10, 13, 16],
    match: "!Spcfsu!Njmft!!!Pof!Boe!Pof!",
    style: {width: "83vw"},
    type: 0,
    videoId: "eAO7CEcCD3s",
    volume: 100,
  },
  {
    title: "Si Me Adverti",
    artist: "Zurdok",
    history: [17, 15, 13, 10, 9, 9, 9, 11, 17],
    match: "!Kbnjsprvbj!!!Dptnjd!Hjsm!",
    startSeconds: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "gZJOe6lEHJE",
    volume: 100,
  },
  {
    title: "Someday",
    artist: "Sugar Ray",
    history: [2, 2, 2, 6, 6, 7, 10, 13, 15],
    match: "!Upoj!Csbyupo!!!Vo.Csfbl!Nz!Ifbsu!",
    startSeconds: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "NQSCKWfJlXs",
    volume: 100,
  },
  {
    title: "Someday We'll Know",
    artist: "New Radicals",
    endSeconds: 215,
    history: [5, 3, 3, 3, 4, 5, 7, 9, 14],
    match: "!Tqjdf!Hjsmt!!!3!Cfdpnf!2!",
    style: {width: "83vw"},
    type: 0,
    videoId: "bDmA8qQKhMY",
    volume: 100,
  },
  {
    title: "Super Trouper",
    artist: "A-Teens",
    history: [16, 14, 12],
    match: "!Xbssfo!H/!!!J!Tipu!Uif!Tifsjgg!",
    style: {width: "83vw"},
    type: 0,
    videoId: "5j1vhCf5XKg",
    volume: 100,
  },
  {
    title: "Tengo Frio",
    artist: "Ely Guerra",
    history: [18, 12, 10],
    match: "!Bqpmmp!Gpvs!Gpsuz!!!Bjo(u!Ubmljo(!(Cpvu!Evc!",
    style: {width: "83vw"},
    type: 0,
    videoId: "foLqysKnIIM",
    volume: 100,
  },
  {
    title: "That's The Way It Is",
    artist: "Celine Dion",
    history: [19, 15, 13, 8, 5, 5, 6],
    match: "!Hjovxjof!!!Qpoz!",
    style: {width: "83vw"},
    type: 0,
    videoId: "T6wbugWrfLU",
    volume: 100,
  },
  {
    title: "The Kids Aren't Alright",
    artist: "The Offspring",
    history: [8, 8, 11, 14, 18],
    match: "!Xbssfo!H/!gfbu/!Bejob!Ipxbse!!!Xibu(t!Mpwf!Hpu!Up!Ep!Xjui!Ju!",
    style: {left: "-5vw", position: "relative", width: "110vw"},
    type: 0,
    videoId: "7iNbnineUCI",
    volume: 100,
  },
  {
    title: "Unpretty",
    artist: "TLC",
    history: [20],
    match: "!Xijuf!Upxo!!!Bcpsu-!Sfusz-!Gbjm@!Zpvs!Xpnbo!",
    style: {width: "83vw"},
    type: 0,
    videoId: "g2gy1Evb1Kg",
    volume: 100,
  },
  {
    title: "Waiting For Tonight",
    artist: "Jennifer Lopez",
    history: [10, 17],
    match: "!Fbtu28!'!Hbcsjfmmf!!!Jg!Zpv!Fwfs!",
    style: {width: "83vw"},
    type: 0,
    videoId: "_66jPJVS4JE",
    volume: 100,
  },
  {
    title: "What's My Age Again?",
    artist: "Blink 182",
    history: [11, 16],
    match: "!Cpz{pof!!!Xpset!",
    style: {width: "83vw"},
    type: 0,
    videoId: "K7l5ZeVVoCA",
    volume: 100,
  },
  {
    title: "When You're Gone",
    artist: "Bryan Adams",
    history: [13, 13, 14, 17, 19],
    match: "!Cmbdltusffu!gfbu/!Es/!Esf!!!Op!Ejhhjuz!",
    style: {width: "83vw"},
    type: 0,
    videoId: "_W2jONIjrM0",
    volume: 100,
  },
]
// .map(element => new Item(element))
//.forEach(item => item.validate())
.forEach(item => {
  const keys = Object.keys(item);
  expect(keys.includes('title')).to.equal(true);
  expect(keys.includes('artist')).to.equal(true);
  expect(keys.includes('history')).to.equal(true);
  expect(keys.includes('match')).to.equal(true);
  expect(keys.includes('style')).to.equal(true);
  expect(keys.includes('type')).to.equal(true);
  expect(keys.includes('videoId')).to.equal(true);
  expect(keys.includes('volume')).to.equal(true);
})
.reduce((map, item) => map.set(item.match, item), new Map());


let uncharted = new List(
  {
    title: "Absolutely Everybody",
    artist: "Vanessa Amorosi",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "Rco1QQShM1Y",
    volume: 100,
  },
  /*{
    title: "Born To Make You Happy",
    artist: "Britney Spears",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "Yy5cKX4jBkQ",
    volume: 100,
  },*/
  {
    title: "Burning Down The House",
    artist: "Tom Jones",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "iYuldgIOelY",
    volume: 100,
  },
  /*{
    title: "Canela",
    artist: "Fey",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "_sgwHcuVCYg",
    volume: 100,
  },*/
  {
    title: "Coma White",
    artist: "Marilyn Manson",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "QQPJYnr48yU",
    volume: 100,
  },
  {
    title: "Don't Call Me Baby",
    artist: "Madison Avenue",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "M1kEjj3Ej68",
    volume: 100,
  },
  {
    title: "Ese Oscuro Objeto Del Deseo",
    artist: "Vertigogo",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "snYOuSoIOO0",
    volume: 100,
  },
  /* 
  {
    title: "From The Bottom Of My Broken Heart",
    artist: "Britney Spears",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "fHPnGqXXUmI",
    volume: 100,
  },
  */
  {
    title: "Guerrilla Radio",
    artist: "Rage Against The Machine",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "Rm1nCYOZB-s",
    volume: 100,
  },
  {
    title: "Let Forever Be",
    artist: "The Chemical Broters",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "s5FyfQDO5g0",
    volume: 100,
  },
  {
    title: "Lullaby",
    artist: "Shawn Mullins",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "hG9C0VwruXE",
    volume: 100,
  },
  /*
  {
    title: "Millenium",
    artist: "Robbie Williams",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "xcWOviMI6Lk",
    volume: 100,
  },
  */
  {
    title: "My Favourite Game",
    artist: "The Cardigans",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "u9WgtlgGAgs",
    volume: 100,
  },
  {
    title: "No Leaf Clover",
    artist: "Metallica",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "Sh5S3OxiE-s",
    volume: 100,
  },
  {
    title: "Ojos Así",
    artist: "Shakira",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "I0ahzYU1xpg",
    volume: 100,
  },
  {
    title: "Pretty Fly",
    artist: "The Offspring",
    priority: 5,
    style: {width: "83vw"},
    type: 0,
    videoId: "QtTR-_Klcq8",
    volume: 100,
  },
  /*
  {
    title: "She's Got Issues",
    artist: "The Offspring",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "SAxPLSvvbXY",
    volume: 100,
  },
  */
  {
    title: "Sitting Down Here",
    artist: "Lene Marlin",
    priority: 1,
    style: {left: "3vw", position: "relative", width: "83vw"},
    type: 0,
    videoId: "ClSVzlObxSc",
    volume: 100,
  },
  {
    title: "So Young",
    artist: "The Corrs",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "TzLTf69vQos",
    volume: 100,
  },
  {
    title: "Thank You",
    artist: "Alanis Morissette",
    priority: 3,
    style: {width: "83vw"},
    type: 0,
    videoId: "OOgpT5rEKIU",
    volume: 100,
  },
  {
    title: "There She Goes",
    artist: "Sixpence None The Richer",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "68MKLkNSMN4",
    volume: 100,
  },
  {
    title: "Ya No Te Quiero",
    artist: "Ana Torroja",
    priority: 1,
    style: {width: "83vw"},
    type: 0,
    videoId: "PIiustuQOlQ",
    volume: 100,
  },
)
// Duplicate an item a certain number of times according to its priority.
// This increases the chances of an item being randomly picked up from the pool.
// For example, an item with a priority of '3' is duplicated 3 times in the pool. 
.map(item => (new Array(item.priority)).fill(item)).flat();
